dist: trusty
sudo: required
language: generic

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"

arch:
  packages:
    - python
    - texlive-core
    - texlive-latexextra
    - texlive-genericextra
    - biber
    - ttf-linux-libertine
    - texlive-bibtexextra
    - ttf-dejavu
    - pygmentize
    - jre9-openjdk

  script:
    - for file in /etc/profile.d/*.sh; do source "${file}"; done && make
    - mv main.pdf $(date +"BT_Franc_Martin_%Y-%m-%d_%H:%M_$TRAVIS_COMMIT.pdf")

before_deploy:
  - export RELEASE_FILE=$(ls BT_Franc_Martin_*.pdf)

deploy:
  name: "text"
  provider: releases
  api_key: "${GH_TOKEN}"
  file: "$RELEASE_FILE"
  skip_cleanup: true
  overwrite: true
  on:
    branch: master
