dist: trusty
sudo: required
language: generic

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"

arch:
  packages:
    - python
    - texlive-core
    - texlive-latexextra
    - texlive-genericextra
    - biber
    - ttf-linux-libertine
    - texlive-bibtexextra
    - ttf-dejavu
    - pygmentize

  script:
    - xelatex -shell-escape -interaction=nonstopmode -halt-on-error main.tex 
    - xelatex -shell-escape -interaction=nonstopmode -halt-on-error main.tex
    - xelatex -shell-escape -interaction=nonstopmode -halt-on-error main.tex
    - mv main.pdf $(date +"bp_francma_%Y-%m-%d_%H:%M_$TRAVIS_COMMIT.pdf")

before_deploy:
  - export RELEASE_FILE=$(ls bp_francma*.pdf)

deploy:
  name: "text"
  provider: releases
  api_key: "${GH_TOKEN}"
  file: "$RELEASE_FILE"
  skip_cleanup: true
  overwrite: true