dist: trusty
sudo: required
language: generic

before_install:
  - sudo add-apt-repository -y ppa:jonathonf/texlive-2016
  - sudo apt-get -y update
  - sudo apt-get -y install texlive-lang-czechslovak
  - sudo apt-get -y install texlive-generic-extra # librarian
  - sudo apt-get -y install texlive-fonts-recommended 
  - sudo apt-get -y install ttf-linux-libertine

script:
  - xetex -fmt=pdfcsplain main.tex
  - xetex -fmt=pdfcsplain main.tex
  - xetex -fmt=pdfcsplain main.tex

deploy:
  name: "text"
  provider: releases
  api_key: "${GH_TOKEN}"
  file: "main.pdf"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true